name: Erlang
on:
  pull_request:
    branches: ['*']
  push:
    branches: [master]

jobs:
  build:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: valitydev/action-setup-thrift@ba661c842d9000844e8107964d712c6ad6cfdf33
        with:
          thrift-version: '0.14.2'

      - uses: erlef/setup-beam@v1.9
        id: beam
        with:
          otp-version: '24'
          rebar3-version: '3.18'

      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            _build/default/rebar3_*_plt

      - run: rebar3 compile
      - run: rebar3 xref
      - run: rebar3 dialyzer
